### ISSUE TITLE
As a user, I want to edit an existing bug tracker issue

### ISSUE THREAD

**Issue by JeremyLoh** [JeremyLoh/window#110]
- [x] On the project page, there will be a list of issues displayed in a table. Each row of the table (issue) will have a row navigation button at the end. This will allow the user to click on "View Issue" and they will be redirected to a dedicated issue page. 

## For Issue page
- [x] Write a supabase query to get issue information using projectId and issue number - https://www.youtube.com/watch?v=Jx8unDjLaKg
    - ![image](https://github.com/JeremyLoh/window/assets/38811217/a7a7d4ad-f3df-4781-9b7c-d1871a18ff18)
- [x] Show details about issue, show project name (instead of project id) 
- [x] There is a "Go Back" button to return to the project page
- [x] A user should only be able to edit the issues that they have created. Edit button should not show if the user did not create the issue
- [x] There is an edit button present that allows for editing. A save button will be present that allows the user to confirm the changes
- [x] The edit form should show in a shadcn dialog box: https://ui.shadcn.com/docs/components/dialog
    - [x] Form in dialog is not working in shadcn https://github.com/shadcn-ui/ui/issues/ 709 - https://shorturl.at/chlw3

Continued from https://github.com/JeremyLoh/window/issues/90
