### ISSUE TITLE
As a user, I want to view a comment section for a bug tracker project issue

### ISSUE THREAD

**Issue by JeremyLoh** [JeremyLoh/window#117]
- [ ] Each user has a profile page (`/bugTracker/profile/USERNAME`), where they are located using their username (`USERNAME`)
    - [ ] Each user will have a default icon for their profile picture
- [ ] Each issue has a comments section
    - [ ] The comments section displays a list of comments with timestamp, user profile picture, username
    - [ ] If the user is logged in, there will be a create comment section where the user can post a new comment
    - [ ] The comments section should be paginated (20 per page) 

## Database changes
Add a new `issue_comment` table that has one to many relationship. One issue will have one or many comments.
- **issue_comment**
    - id (uuid)
    - issue_id (FK with `issue` table)
    - user_id (FK with `user` table, the user who has made the comment)
    - created_at (set to `now()`)
    - updated_at (set to NULL)
    - content

To display comments, just order by column `created_at` for a single issue
