### ISSUE TITLE
As a user, I want to create an account for Bug Tracker app

### ISSUE THREAD

**Issue by JeremyLoh** [JeremyLoh/window#83]
Allow user to navigate to "Bug Tracker" feature
- [x] Update Nav Bar to just be the app name and current feature the user is on (e.g. "Bug Tracker", "Life", "Exchange"). Navigation is through clicking on the "Window" app name
- [x] Add link to "Bug Tracker" page and corresponding page route

Use NextJS 13 "app" directory for bug tracker app
https://www.youtube.com/watch?v=EOppukfgL_o

# Bug Tracker page (/bugTracker)
- [ ] Have introduction page about bug tracker features, possible screenshots in the future
- [x] View "Login" or "Sign up" buttons
- [x] Add tests for navigation to Login page
- [x] Add tests for navigation to Sign Up page (it is disabled, should be run manually) (`it.skip`)

"Sign up" (/bugTracker/signUp)
- [x] Redirect to page where user can create an account, using email and password
- [x] After sign up, the user is redirected to login page /bugTracker/login

"Login" (/bugTracker/login)
- [x] Allow user to login to an existing account, after email is confirmed
- [x] Prompt user to confirm their email if they try to login (with alert)
    - [x] There is a "Resend Email" button in the popup
- [x] After login, the user is redirected to their bug tracker dashboard (/bugTracker/dashboard)
- [x] The dashboard should redirect to /bugTracker/login if the user is not logged in

## Authentication
- Supabase - https://supabase.com/
- [x] Add environment variables to Vercel for Supabase! https://supabase.com/docs/guides/auth/auth-helpers/nextjs

## Testing
- [ ] How to implement authentication in Cypress E2E tests? #6177 - https://github.com/orgs/supabase/discussions/6177
Add Cypress tests

## To read
- [ ] https://www.reddit.com/r/nextjs/comments/svr3zy/authentication_with_nextjs_the_dos_and_donts_and/
