### ISSUE TITLE
As a user, I want to view my bug tracker dashboard page and create a new project, delete an existing project

### ISSUE THREAD

**Issue by JeremyLoh** [JeremyLoh/window#85]
On the dashboard page, the user should be able to do the following:
- [x] View a list of projects that are available for them
- [x] Create a new project from the list of projects available for them. After project creation, they will be redirected to a page describing the project and the bugs created for the project
- [x] For an existing project, the user should have a way to delete it from the list of projects. There should be a confirmation before actual deletion
- [x] Setup a trigger to insert new users into the "public.user" table in Supabase
    - [X]  Using PostgreSQL triggers to automate processes with Supabase - https://www.youtube.com/watch?v=0N6M5BBe9AE 
- [x] Setup RLS (Row Level Security) for data in Supabase tables - https://www.youtube.com/watch?v=Ow_Uzedfohk

e.g. UI for Project management: https://gitlab.com/gitlab-org/gitlab/-/issues/29664

## Create design for UI using Figma

Figma: Introduction to Design Systems
https://www.youtube.com/playlist?list=PLXDU_eVOJTx6vqOWJSWH87Zb5-riiG63A

## Database reference
- [Normalization - 1NF, 2NF, 3NF and 4NF](https://www.youtube.com/watch?v=UrYLYV7WSHM)
    - 1st Normal Form (1NF)
        - Each column to be single valued (e.g. cannot be "a,b")
        - Entries in a column are same type
        - Rows can be uniquely identified - add unique id, or add more columns to make unique
            - The order of the rows and the order of the columns are not relevant
    - 2nd Normal Form (2NF)
        - All attributes (non-key columns) are dependent on key
    - 3rd Normal Form (3NF)
        - All fields (columns) can be determined only by the key in the table and no other column
    - 4th Normal Form (4NF)
        - No multi-valued dependencies
- [Supabase - One to Many Relationship - SupabaseTips](https://www.youtube.com/watch?v=5VrF9OVQ6rg)
- [Supabase Docs (Database) - Tables and Data](https://supabase.com/docs/guides/database/tables)
- [Implement Authorization using Row Level Security with Supabase](https://www.youtube.com/watch?v=Ow_Uzedfohk)
