### ISSUE TITLE
As a user, I want to delete my bug tracker account

### ISSUE THREAD

**Issue by JeremyLoh** [JeremyLoh/window#88]
- [x] Have an option to view account details (Profile) after login
- [x] There should be a "Delete Account" in red button, that will prompt for confirm delete account
- [x] It deletes an account in the public.user table. It should also remove the entry in auth.users (Supabase auth users table)
    - Add a table where we will add an entry and this will make a trigger run to delete the user
