### ISSUE TITLE
As a user, I want to view all bug tracker issues for a project and perform Create and Read operations

### ISSUE THREAD

**Issue by JeremyLoh** [JeremyLoh/window#90]
- [x] For each project, a list of issues will be presented on the project page, using https://ui.shadcn.com/docs/components/data-table with pagniation - https://github.com/TanStack/table/discussions/2029
    - [x] Truncate name, description to show only at most 2 lines (mobile), 3 lines (for md screen), 4 lines for bigger screen widths, ellipses should show for name, description with more than this line count 
    - [x] There is a line clamp in tailwindcss, already part of the package, no need to install this plugin anymore! https://tailwindcss.com/blog/multi-line-truncation-with-tailwindcss-line-clamp (https://stackoverflow.com/questions/71093772/how-to-truncate-text-in-tailwindcss)
- [x] Create client function to create new issue in "issue" table
- [x] Query supabase for list of existing issues for the project and display in data table
- [x] A new issue can be created from a button press "Add Issue" button on the project page
- [x] Each issue will have the following information:
    - Name
    - Description
    - Status
    - Priority (None, Lowest, Low, Medium, High, Highest)
    - Created At timestamp
    - Link to the user id that created the issue
    - The project the issue was created for
    - Issue number (based on project)
- [x] You cannot delete an issue after creating it. Can only mark it as "Closed" status

# Database Changes
- [x] Create a table for "issue", stores 
    - name
    - description
    - status (foreign key with issue_status table)
    - priority (foreign key with issue_priority table)
    - created_at
    - created_by_user_id (foreign key with user table, id)
    - project_id (foreign key with project table, id)
    - issue_number (starts from 1, based on the number of issues for a project_id)
- [x] Create a table for "issue_priority"
    - Have the possible values for a issue priority present in this table
    - Have description for the priority
- [x] Create a table for "issue_status"
    - Have the possible values for a issue status in this table: None, Closed, New, Backlog, Ready, In Progress, In Review, Done

Each issue should be numbered in increasing order based on the project it is created for:
Call this function for getting the issue count, when creating a new issue for the project
```plpgsql
create or replace function get_issue_count(project_id_input uuid) returns bigint as $$
  begin
    return (SELECT COUNT(*) FROM issue
    WHERE issue.project_id = project_id_input);
  end;
$$ language plpgsql;
```
![image](https://github.com/JeremyLoh/window/assets/38811217/7f5ceeef-675b-45e5-9dfe-1a894331a418)
https://supabase.com/docs/guides/database/functions
 Create PostgreSQL Functions with Supabase  - https://www.youtube.com/watch?v=MJZCCpCYEqk

To Watch
- [x] [Complete guide to Database Normalization in SQL](https://www.youtube.com/watch?v=rBPQ5fg_kiY)
    - 20:00 / 40:50
