### ISSUE TITLE
As a user, once I login to bug tracker, the /bugTracker route should show "Dashboard" button instead of "Login" and "Sign Up"

### ISSUE THREAD

**Issue by JeremyLoh** [JeremyLoh/window#97]
- [x] "Login" and "Sign Up" button on /bugTracker page should appear when user is not logged in
- [x] "Login" and "Sign Up" button on /bugTracker page should not be present when the user is logged in. There should be a "Dashboard" button instead
- [x] When the user logs out using the navbar, the "Login" and "Sign Up" button appears
- [x] In projects, there should be some way to navigate to dashboard page
