### ISSUE TITLE
As a user, I want to set up a username for my bug tracker account during sign up

### ISSUE THREAD

**Issue by JeremyLoh** [JeremyLoh/window#98]
- [x] For the bug tracker sign up page, there should be a field for the user to give a display name (username) that needs to be stored in the "user" table. The username needs to be passed in a way that the trigger used to insert a new record into public.user table, also has the username to insert
- [x] The username should be limited to be max of 40 characters. Min of 1 character. Add test for this for length 41, it should reject with error in form validation
- [x] The name provided for username should be used for dashboard, profile page, and show up for project page
- [x] Update existing test for sign up, add test for username input in sign up

## Currently Supabase doesn't really have a good way to check if the user exists?
  - Relevant Discussion https://github.com/supabase/supabase-js/issues/296
  - Either use Yup to validate, or call some function in handleSubmit to check for username - https://stackoverflow.com/questions/65039849/validate-if-username-already-exists-while-typing-using-formik-and-yup

# Database Changes
- [x] signUp custom fields raw_user_meta_data #7113 - https://github.com/orgs/supabase/discussions/7113
- [x] Additional information is passed to supabase auth sign up function (`supabase.auth.signUp`). The username can be given as metadata. This metadata can be pulled in the trigger function used to add a new user into the public.user table (when a new user signs up and is added to the auth.users table)
    - https://supabase.com/docs/guides/auth/managing-user-data#accessing-user-metadata
    - https://stackoverflow.com/questions/73185811/add-aditional-user-information-when-signup-supabase
    - ![image](https://github.com/JeremyLoh/window/assets/38811217/0bb704c5-0a84-4853-b3b3-14101e8cb84e)

![image](https://github.com/JeremyLoh/window/assets/38811217/999c9ff0-2705-4942-808d-4e9a176cf894)
Querying JSON data is similar to querying other data, with a few other features to access nested values.
Postgres support a range of [JSON functions and operators](https://www.postgresql.org/docs/current/functions-json.html). For example, the -> operator returns values as jsonb data. If you want the data returned as text, use the ->> operator.
https://supabase.com/docs/guides/database/json#query-json-data
